version: '3.9'

services:
  learning-dapr-1:
    image: geircodeacr.azurecr.io/learning-dapr:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}      
        GEIRCODE_AZURE_DEVOPS_TOKEN: ${GEIRCODE_AZURE_DEVOPS_TOKEN}
    restart: always
    container_name: learning-dapr-1
    # Update: It's now possible to set DNS in Docker Desktop
    # dns: # "az login" workaround for the gnarly bug: https://github.com/microsoft/WSL/issues/4285
    #   - 8.8.8.8    
    network_mode: "bridge"
    environment:
      - EXAMPLE_CONFIG=/test/test
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - KUBECONFIG=/kubeconfig/config
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - git_repositories:/git      
      - "vscode_server_extensions:/root/.vscode-server/extensions"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/secrets/kubeconfig:/kubeconfig"
    # ports: 
    #   - 5003:5003
    # networks:
    #   - geircode_common_network

volumes:
  git_repositories: {}    
  vscode_server_extensions: {}