version: '3.7'

services:
  learning-dapr-codespace-filecontainer:
    image: geircodeacr.azurecr.io/learning-dapr-codespace-filecontainer:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: learning-dapr-codespace-filecontainer-1
    networks:
      - learning-dapr-codespace-filecontainer-network      

networks:
  learning-dapr-codespace-filecontainer-network:
    name: learning-dapr-codespace-filecontainer-network    
    